import type { ScheduleItem, Zone, Bapteme } from './types';
import { COLORS } from './theme';

export const SCHEDULE: ScheduleItem[] = [
  {
    id: '1',
    time: '07:30',
    endTime: '09:00',
    title: 'Ouverture des portes',
    description: 'Accès paddocks exposants',
    tag: 'ACCÈS',
    tagColor: COLORS.textSecondary,
  },
  {
    id: '2',
    time: '09:00',
    endTime: '10:30',
    title: 'TrackDay - Session 1',
    description: 'Voitures GT & Supercars sur circuit',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '3',
    time: '10:30',
    endTime: '12:00',
    title: 'Baptêmes de piste',
    description: 'LMP2, Porsche GT3 Cup, BMW M4 Comp',
    tag: 'BAPTÊME',
    tagColor: COLORS.accent,
    zone: 'baptemes',
  },
  {
    id: '4',
    time: '11:00',
    endTime: '11:30',
    title: 'Défilé Hypercars',
    description: 'Parade exclusive dans les paddocks',
    tag: 'SHOW',
    tagColor: '#A855F7',
    zone: 'paddock',
  },
  {
    id: '5',
    time: '12:00',
    endTime: '13:30',
    title: 'Pause midi',
    description: 'Food trucks & stands restauration',
    tag: 'FOOD',
    tagColor: COLORS.success,
    zone: 'food',
  },
  {
    id: '6',
    time: '13:30',
    endTime: '15:00',
    title: 'TrackDay - Session 2',
    description: 'Sessions libres circuit',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '7',
    time: '15:00',
    endTime: '16:30',
    title: 'Vote Best Car',
    description: 'Élisez la plus belle voiture du BDG',
    tag: 'VOTE',
    tagColor: COLORS.accent,
  },
  {
    id: '8',
    time: '17:00',
    endTime: '17:30',
    title: 'Remise des prix',
    description: 'Cérémonie de clôture',
    tag: 'SHOW',
    tagColor: '#A855F7',
    zone: 'paddock',
  },
  {
    id: '9',
    time: '18:00',
    title: 'Fin de l\'événement',
    description: 'À l\'année prochaine !',
    tag: 'FIN',
    tagColor: COLORS.textSecondary,
  },
];

export const ZONES: Zone[] = [
  {
    id: 'paddock',
    name: 'Paddock Principal',
    description: 'Expo Supercars & Hypercars',
    info: '450+ voitures',
    color: COLORS.zonePaddock,
    coordinates: { latitude: 50.4372, longitude: 5.9714 },
  },
  {
    id: 'baptemes',
    name: 'Zone Baptêmes',
    description: 'Départ baptêmes passager',
    info: 'LMP2 · GT3 · M4',
    color: COLORS.zoneBapteme,
    coordinates: { latitude: 50.4365, longitude: 5.9700 },
  },
  {
    id: 'stands',
    name: 'Stands Pros',
    description: 'Pièces, tuning, performance',
    info: '35 exposants',
    color: COLORS.zoneStands,
    coordinates: { latitude: 50.4380, longitude: 5.9720 },
  },
  {
    id: 'food',
    name: 'Food Court',
    description: 'Food trucks & bar',
    info: '12 stands',
    color: COLORS.zoneFood,
    coordinates: { latitude: 50.4375, longitude: 5.9730 },
  },
  {
    id: 'vip',
    name: 'Paddock VIP',
    description: 'Accès exclusif bracelet VIP',
    info: 'Hypercars only',
    color: COLORS.zoneVIP,
    coordinates: { latitude: 50.4368, longitude: 5.9710 },
  },
];

export const BAPTEMES: Bapteme[] = [
  {
    id: 'lmp2',
    carModel: 'Prototype LMP2 Biplace',
    provider: 'AF MotorSport',
    price: 220,
    duration: '15 min',
    laps: 3,
    description: '200 CH pour moins de 600 kg. Sensations extrêmes garanties + vidéo 360°.',
    availableSlots: [],
  },
  {
    id: 'gt3cup',
    carModel: 'Porsche 991 GT3 Cup',
    provider: 'AF MotorSport',
    price: 180,
    duration: '12 min',
    laps: 3,
    description: 'La pure-sang de course Porsche sur le plus beau circuit du monde.',
    availableSlots: [],
  },
  {
    id: 'm4comp',
    carModel: 'BMW M4 Competition',
    provider: 'Motortech',
    price: 150,
    duration: '12 min',
    laps: 3,
    description: 'M4 armée pour la piste. Puissance, freinages précis, trajectoires parfaites.',
    availableSlots: [],
  },
  {
    id: 'adrenaline',
    carModel: 'Adrénaline Experience',
    provider: 'K\'Mystik',
    price: 195,
    duration: '20 min',
    laps: 4,
    description: '4 tours inoubliables + caméra embarquée avec télémétrie et vue route.',
    availableSlots: [],
  },
];
