import type { ScheduleItem, Zone, Bapteme, CircuitZone } from './types';
import { COLORS } from './theme';

export const SCHEDULE: ScheduleItem[] = [
  {
    id: '1',
    time: '07:30',
    endTime: '09:00',
    title: 'Ouverture des portes',
    description: 'Acces paddocks exposants',
    tag: 'ACCES',
    tagColor: COLORS.textSecondary,
  },
  {
    id: '2',
    time: '09:00',
    endTime: '10:30',
    title: 'TrackDay - Session 1',
    description: 'Voitures GT & Supercars sur circuit',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '3',
    time: '10:30',
    endTime: '12:00',
    title: 'Baptemes de piste',
    description: 'LMP2, Porsche GT3 Cup, BMW M4 Comp',
    tag: 'BAPTEME',
    tagColor: COLORS.zoneBapteme,
    zone: 'baptemes',
  },
  {
    id: '4',
    time: '11:00',
    endTime: '11:30',
    title: 'Defile Hypercars',
    description: 'Parade exclusive dans les paddocks',
    tag: 'SHOW',
    tagColor: COLORS.zoneStands,
    zone: 'paddock',
  },
  {
    id: '5',
    time: '12:00',
    endTime: '13:30',
    title: 'Pause midi',
    description: 'Food trucks & stands restauration',
    tag: 'FOOD',
    tagColor: COLORS.success,
    zone: 'food',
  },
  {
    id: '6',
    time: '13:30',
    endTime: '15:00',
    title: 'TrackDay - Session 2',
    description: 'Sessions libres circuit',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '7',
    time: '15:00',
    endTime: '16:30',
    title: 'Vote Best Car',
    description: 'Elisez la plus belle voiture du BDG',
    tag: 'VOTE',
    tagColor: COLORS.zoneBapteme,
  },
  {
    id: '8',
    time: '17:00',
    endTime: '17:30',
    title: 'Remise des prix',
    description: 'Ceremonie de cloture',
    tag: 'SHOW',
    tagColor: COLORS.zoneStands,
    zone: 'paddock',
  },
  {
    id: '9',
    time: '18:00',
    title: 'Fin de l\'evenement',
    description: 'A l\'annee prochaine !',
    tag: 'FIN',
    tagColor: COLORS.textSecondary,
  },
];

export const ZONES: Zone[] = [
  {
    id: 'paddock',
    name: 'Paddock Principal',
    description: 'Expo Supercars & Hypercars',
    info: '450+ voitures',
    color: COLORS.zonePaddock,
    coordinates: { latitude: 50.4372, longitude: 5.9714 },
  },
  {
    id: 'baptemes',
    name: 'Zone Baptemes',
    description: 'Depart baptemes passager',
    info: 'LMP2 / GT3 / M4',
    color: COLORS.zoneBapteme,
    coordinates: { latitude: 50.4365, longitude: 5.9700 },
  },
  {
    id: 'stands',
    name: 'Stands Pros',
    description: 'Pieces, tuning, performance',
    info: '35 exposants',
    color: COLORS.zoneStands,
    coordinates: { latitude: 50.4380, longitude: 5.9720 },
  },
  {
    id: 'food',
    name: 'Food Court',
    description: 'Food trucks & bar',
    info: '12 stands',
    color: COLORS.zoneFood,
    coordinates: { latitude: 50.4375, longitude: 5.9730 },
  },
  {
    id: 'vip',
    name: 'Paddock VIP',
    description: 'Acces exclusif bracelet VIP',
    info: 'Hypercars only',
    color: COLORS.zoneVIP,
    coordinates: { latitude: 50.4368, longitude: 5.9710 },
  },
];

// Detailed circuit zones for the interactive 3D map
export const CIRCUIT_ZONES: CircuitZone[] = [
  {
    id: 'la-source',
    name: 'La Source',
    type: 'corner',
    description: 'Epingle serree apres la ligne de depart',
    details: [
      'Virage en epingle a droite',
      'Premiere zone de freinage',
      'Vitesse: ~65 km/h au sommet',
      'Point de depassement strategique',
    ],
    color: COLORS.primary,
    mapPosition: { x: 82, y: 12 },
    coordinates: { latitude: 50.4372, longitude: 5.9714 },
  },
  {
    id: 'eau-rouge',
    name: 'Eau Rouge / Raidillon',
    type: 'corner',
    description: 'Le virage le plus celebre du monde',
    details: [
      'Enchainement gauche-droite en montee',
      'Pris a fond par les F1 (~300 km/h)',
      'Denivele de 40m en quelques secondes',
      'Zone spectacle privilegiee lors du TrackDay',
    ],
    color: COLORS.zoneEauRouge,
    mapPosition: { x: 70, y: 25 },
    coordinates: { latitude: 50.4340, longitude: 5.9700 },
    scheduleIds: ['2', '6'],
  },
  {
    id: 'kemmel',
    name: 'Ligne droite de Kemmel',
    type: 'straight',
    description: 'Plus longue ligne droite du circuit',
    details: [
      'Vitesse max: ~330 km/h en F1',
      'Zone DRS en competition',
      'Point de vue sur les Ardennes',
      'Zone ideale pour les photos de vitesse',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 50, y: 18 },
    coordinates: { latitude: 50.4350, longitude: 5.9650 },
  },
  {
    id: 'les-combes',
    name: 'Les Combes',
    type: 'corner',
    description: 'Chicane technique en haut du circuit',
    details: [
      'Enchainement gauche-droite-gauche',
      'Zone de freinage intense',
      'Point culminant du circuit',
      'Vue panoramique sur la vallee',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 28, y: 10 },
    coordinates: { latitude: 50.4355, longitude: 5.9600 },
  },
  {
    id: 'malmedy',
    name: 'Malmedy',
    type: 'corner',
    description: 'Virage rapide en descente',
    details: [
      'Virage a droite rapide',
      'Transition vers la partie basse',
      'Vitesse: ~200 km/h',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 18, y: 22 },
    coordinates: { latitude: 50.4345, longitude: 5.9560 },
  },
  {
    id: 'rivage',
    name: 'Rivage',
    type: 'corner',
    description: 'Epingle en descente vers Pouhon',
    details: [
      'Virage a gauche serre',
      'Zone technique importante',
      'Transition vers la section rapide',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 12, y: 35 },
    coordinates: { latitude: 50.4330, longitude: 5.9545 },
  },
  {
    id: 'pouhon',
    name: 'Pouhon',
    type: 'corner',
    description: 'Double gauche rapide et spectaculaire',
    details: [
      'Virage a gauche en appui (190+ km/h)',
      'Test ultime pour l\'aerodynamique',
      'Zone a forte charge laterale',
      'Spectacle garanti lors du TrackDay',
    ],
    color: COLORS.primary,
    mapPosition: { x: 8, y: 52 },
    coordinates: { latitude: 50.4310, longitude: 5.9540 },
    scheduleIds: ['2', '6'],
  },
  {
    id: 'fagnes',
    name: 'Les Fagnes',
    type: 'corner',
    description: 'Chicane rapide en S',
    details: [
      'Enchainement technique',
      'Zone de decceleration rapide',
      'Nom tire des hautes fagnes proches',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 15, y: 65 },
    coordinates: { latitude: 50.4295, longitude: 5.9560 },
  },
  {
    id: 'stavelot',
    name: 'Stavelot',
    type: 'corner',
    description: 'Double droite vers Blanchimont',
    details: [
      'Virage a droite en deux temps',
      'Acceleration progressive',
      'Preparation pour Blanchimont',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 28, y: 78 },
    coordinates: { latitude: 50.4285, longitude: 5.9590 },
  },
  {
    id: 'blanchimont',
    name: 'Blanchimont',
    type: 'corner',
    description: 'Courbe ultra-rapide a gauche',
    details: [
      'Pris a plus de 300 km/h en F1',
      'Un des virages les plus rapides au monde',
      'Gros engagement du pilote requis',
      'Spectacle impressionnant',
    ],
    color: COLORS.primary,
    mapPosition: { x: 52, y: 85 },
    coordinates: { latitude: 50.4290, longitude: 5.9660 },
  },
  {
    id: 'bus-stop',
    name: 'Bus Stop Chicane',
    type: 'corner',
    description: 'Chicane finale avant la ligne',
    details: [
      'Chicane droite-gauche lente',
      'Derniere zone de freinage',
      'Zone de depassement possible',
      'Entree dans la zone des paddocks',
    ],
    color: COLORS.primary,
    mapPosition: { x: 78, y: 75 },
    coordinates: { latitude: 50.4360, longitude: 5.9710 },
  },
  {
    id: 'pit-lane',
    name: 'Pit Lane',
    type: 'paddock',
    description: 'Allee des stands et depart baptemes',
    details: [
      'Depart des sessions TrackDay',
      'Zone de ravitaillement',
      'Point de depart des baptemes',
      'Acces reserve aux pilotes inscrits',
    ],
    color: COLORS.zonePitLane,
    mapPosition: { x: 85, y: 45 },
    coordinates: { latitude: 50.4370, longitude: 5.9712 },
    polygon: [
      { latitude: 50.4368, longitude: 5.9705 },
      { latitude: 50.4372, longitude: 5.9705 },
      { latitude: 50.4372, longitude: 5.9720 },
      { latitude: 50.4368, longitude: 5.9720 },
    ],
    scheduleIds: ['2', '3', '6'],
  },
  {
    id: 'paddock-principal',
    name: 'Paddock Principal',
    type: 'paddock',
    description: 'Exposition 450+ Supercars & Hypercars',
    details: [
      '450+ voitures exposees',
      'Lamborghini, Ferrari, Porsche, McLaren...',
      'Vote Best Car de 15h a 16h30',
      'Defile Hypercars a 11h',
      'Acces libre avec le billet',
    ],
    color: COLORS.zonePaddock,
    mapPosition: { x: 90, y: 30 },
    coordinates: { latitude: 50.4375, longitude: 5.9720 },
    polygon: [
      { latitude: 50.4373, longitude: 5.9716 },
      { latitude: 50.4378, longitude: 5.9716 },
      { latitude: 50.4378, longitude: 5.9726 },
      { latitude: 50.4373, longitude: 5.9726 },
    ],
    scheduleIds: ['1', '4', '7', '8'],
    cars: ['Lamborghini Revuelto', 'Ferrari SF90', 'Porsche 911 GT3 RS', 'McLaren 750S'],
  },
  {
    id: 'zone-baptemes',
    name: 'Zone Baptemes',
    type: 'paddock',
    description: 'Depart baptemes passager sur circuit',
    details: [
      'Prototype LMP2 - 220EUR / 3 tours',
      'Porsche 991 GT3 Cup - 180EUR / 3 tours',
      'BMW M4 Competition - 150EUR / 3 tours',
      'Adrenaline Experience - 195EUR / 4 tours',
      'Inscription sur place ou via l\'app',
    ],
    color: COLORS.zoneBapteme,
    mapPosition: { x: 92, y: 55 },
    coordinates: { latitude: 50.4365, longitude: 5.9700 },
    polygon: [
      { latitude: 50.4362, longitude: 5.9694 },
      { latitude: 50.4368, longitude: 5.9694 },
      { latitude: 50.4368, longitude: 5.9706 },
      { latitude: 50.4362, longitude: 5.9706 },
    ],
    scheduleIds: ['3'],
  },
  {
    id: 'stands-pros',
    name: 'Village Exposants',
    type: 'service',
    description: '35 stands professionnels',
    details: [
      'Pieces & accessoires auto',
      'Preparateurs & tuners',
      'Merch officiel BDG',
      'Sponsors & partenaires',
      'Paiement en BDG Coins',
    ],
    color: COLORS.zoneStands,
    mapPosition: { x: 95, y: 15 },
    coordinates: { latitude: 50.4380, longitude: 5.9725 },
    polygon: [
      { latitude: 50.4378, longitude: 5.9720 },
      { latitude: 50.4383, longitude: 5.9720 },
      { latitude: 50.4383, longitude: 5.9732 },
      { latitude: 50.4378, longitude: 5.9732 },
    ],
    stands: ['Motortech', 'AF MotorSport', 'Purefect', 'K\'Mystik'],
  },
  {
    id: 'food-court',
    name: 'Food Court',
    type: 'service',
    description: '12 food trucks & bar',
    details: [
      '12 food trucks varies',
      'Bar & boissons',
      'Zone assise couverte',
      'Paiement exclusif en BDG Coins',
      'Ouvert de 09h a 18h',
    ],
    color: COLORS.zoneFood,
    mapPosition: { x: 98, y: 42 },
    coordinates: { latitude: 50.4378, longitude: 5.9735 },
    polygon: [
      { latitude: 50.4376, longitude: 5.9730 },
      { latitude: 50.4381, longitude: 5.9730 },
      { latitude: 50.4381, longitude: 5.9740 },
      { latitude: 50.4376, longitude: 5.9740 },
    ],
    scheduleIds: ['5'],
  },
  {
    id: 'vip-lounge',
    name: 'Espace VIP',
    type: 'grandstand',
    description: 'Lounge exclusif bracelet VIP',
    details: [
      'Vue directe sur la pit lane',
      'Catering premium inclus',
      'Meet & greet pilotes',
      'Acces paddock Hypercars',
      'Cadeau BDG exclusif',
    ],
    color: COLORS.zoneVIP,
    mapPosition: { x: 88, y: 60 },
    coordinates: { latitude: 50.4368, longitude: 5.9710 },
    polygon: [
      { latitude: 50.4365, longitude: 5.9706 },
      { latitude: 50.4371, longitude: 5.9706 },
      { latitude: 50.4371, longitude: 5.9714 },
      { latitude: 50.4365, longitude: 5.9714 },
    ],
  },
];

export const BAPTEMES: Bapteme[] = [
  {
    id: 'lmp2',
    carModel: 'Prototype LMP2 Biplace',
    provider: 'AF MotorSport',
    price: 220,
    duration: '15 min',
    laps: 3,
    description: '200 CH pour moins de 600 kg. Sensations extremes garanties + video 360.',
    availableSlots: [],
  },
  {
    id: 'gt3cup',
    carModel: 'Porsche 991 GT3 Cup',
    provider: 'AF MotorSport',
    price: 180,
    duration: '12 min',
    laps: 3,
    description: 'La pure-sang de course Porsche sur le plus beau circuit du monde.',
    availableSlots: [],
  },
  {
    id: 'm4comp',
    carModel: 'BMW M4 Competition',
    provider: 'Motortech',
    price: 150,
    duration: '12 min',
    laps: 3,
    description: 'M4 armee pour la piste. Puissance, freinages precis, trajectoires parfaites.',
    availableSlots: [],
  },
  {
    id: 'adrenaline',
    carModel: 'Adrenaline Experience',
    provider: 'K\'Mystik',
    price: 195,
    duration: '20 min',
    laps: 4,
    description: '4 tours inoubliables + camera embarquee avec telemetrie et vue route.',
    availableSlots: [],
  },
];
