import type { ScheduleItem, Zone, Bapteme, CircuitZone, MapPoi } from './types';
import { COLORS } from './theme';

export const SCHEDULE: ScheduleItem[] = [
  {
    id: '1',
    time: '09:00',
    endTime: '12:00',
    title: 'TrackDay - Session 1',
    description: 'Supercars & GT sur le circuit de Spa-Francorchamps',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '2',
    time: '09:30',
    endTime: '11:00',
    title: 'Show Drift - Session 1',
    description: 'Demos de drift au Paddock Drift',
    tag: 'DRIFT',
    tagColor: COLORS.zoneBapteme,
    zone: 'paddock-drift',
  },
  {
    id: '3',
    time: '11:45',
    title: 'Show FMX',
    description: 'Freestyle Motocross - Sauts & figures',
    tag: 'FMX',
    tagColor: COLORS.zoneEauRouge,
    zone: 'show-fmx',
  },
  {
    id: '4',
    time: '12:00',
    endTime: '13:00',
    title: 'Parade Super Car & Hyper Car',
    description: 'Défilé exceptionnel sur le circuit',
    tag: 'PARADE',
    tagColor: COLORS.zoneStands,
    zone: 'circuit',
  },
  {
    id: '5',
    time: '13:00',
    title: 'Show FMX',
    description: 'Freestyle Motocross - Session 2',
    tag: 'FMX',
    tagColor: COLORS.zoneEauRouge,
    zone: 'show-fmx',
  },
  {
    id: '6',
    time: '13:00',
    endTime: '17:00',
    title: 'TrackDay - Session 2',
    description: 'Sessions circuit apres-midi',
    tag: 'PISTE',
    tagColor: COLORS.primary,
    zone: 'circuit',
  },
  {
    id: '7',
    time: '13:30',
    endTime: '14:30',
    title: 'Show Drift - Session 2',
    description: 'Demos de drift au Paddock Drift',
    tag: 'DRIFT',
    tagColor: COLORS.zoneBapteme,
    zone: 'paddock-drift',
  },
  {
    id: '8',
    time: '14:30',
    title: 'Show Dragster',
    description: 'Démonstrations Dragster au Paddock Drift',
    tag: 'DRAGSTER',
    tagColor: COLORS.zonePitLane,
    zone: 'paddock-drift',
  },
  {
    id: '9',
    time: '15:00',
    title: 'Show FMX',
    description: 'Freestyle Motocross - Session 3',
    tag: 'FMX',
    tagColor: COLORS.zoneEauRouge,
    zone: 'show-fmx',
  },
  {
    id: '10',
    time: '15:00',
    endTime: '16:00',
    title: 'Show Drift - Session 3',
    description: 'Demos de drift au Paddock Drift',
    tag: 'DRIFT',
    tagColor: COLORS.zoneBapteme,
    zone: 'paddock-drift',
  },
  {
    id: '11',
    time: '16:00',
    title: 'Show Dragster',
    description: 'Démonstrations Dragster - Session 2',
    tag: 'DRAGSTER',
    tagColor: COLORS.zonePitLane,
    zone: 'paddock-drift',
  },
  {
    id: '12',
    time: '16:30',
    endTime: '17:00',
    title: 'Show Final Drift',
    description: 'Show Final Raul + Soul + Drifteurs',
    tag: 'DRIFT',
    tagColor: COLORS.primary,
    zone: 'paddock-drift',
  },
  {
    id: '13',
    time: '17:00',
    title: 'Show FMX',
    description: 'Freestyle Motocross - Dernier show',
    tag: 'FMX',
    tagColor: COLORS.zoneEauRouge,
    zone: 'show-fmx',
  },
  {
    id: '14',
    time: '17:15',
    endTime: '18:00',
    title: 'Pitwalk & Gridwalk',
    description: 'Accès à la pit lane et grille de départ',
    tag: 'PITWALK',
    tagColor: COLORS.zoneVIP,
    zone: 'circuit',
  },
];

export const ZONES: Zone[] = [
  {
    id: 'paddock-f1',
    name: 'Paddock / Box F1',
    description: 'Expo Supercars & Hypercars',
    info: '450+ voitures',
    color: COLORS.zonePaddock,
    coordinates: { latitude: 50.444435, longitude: 5.965445 },
  },
  {
    id: 'paddock-drift',
    name: 'Paddock Drift',
    description: 'Zone drift & demo',
    info: 'Show drift',
    color: COLORS.zoneBapteme,
    coordinates: { latitude: 50.440091, longitude: 5.969598 },
  },
  {
    id: 'paddock-violet',
    name: 'Paddock Violet',
    description: 'Stands pros & exposition',
    info: 'Stands pro',
    color: COLORS.zoneStands,
    coordinates: { latitude: 50.441353, longitude: 5.968920 },
  },
  {
    id: 'fan-zone',
    name: 'Fan Zone',
    description: 'Espace fans & animations',
    info: 'Stands & activites',
    color: COLORS.zoneFood,
    coordinates: { latitude: 50.443429, longitude: 5.970071 },
  },
  {
    id: 'kids',
    name: 'Kids Zone',
    description: 'Espace enfants',
    info: 'Activites enfants',
    color: COLORS.success,
    coordinates: { latitude: 50.444252, longitude: 5.970595 },
  },
];

// Detailed circuit zones for the interactive 3D map
export const CIRCUIT_ZONES: CircuitZone[] = [
  // === TRIBUNES ===
  {
    id: 'tribune-f1',
    name: 'Tribune F1',
    type: 'grandstand',
    description: 'Tribune principale vue sur la ligne droite',
    details: ['Vue panoramique sur la pit lane', 'Places assises couvertes', 'Écran géant'],
    color: COLORS.zoneVIP,
    mapPosition: { x: 60, y: 20 },
    coordinates: { latitude: 50.443490, longitude: 5.965006 },
  },
  {
    id: 'tribune-endurance',
    name: 'Tribune Endurance',
    type: 'grandstand',
    description: 'Tribune vue sur le virage',
    details: ['Vue sur la chicane', 'Ambiance course'],
    color: COLORS.zoneVIP,
    mapPosition: { x: 75, y: 30 },
    coordinates: { latitude: 50.444879, longitude: 5.968244 },
  },
  {
    id: 'tribune-raidillon',
    name: 'Tribune Raidillon',
    type: 'grandstand',
    description: 'Vue imprenable sur Eau Rouge / Raidillon',
    details: ['Le meilleur point de vue du circuit', 'Vue sur le célèbre enchaînement Eau Rouge'],
    color: COLORS.zoneVIP,
    mapPosition: { x: 85, y: 70 },
    coordinates: { latitude: 50.441234, longitude: 5.972843 },
  },
  // === SHOWS ===
  {
    id: 'show-fmx',
    name: 'Show FMX',
    type: 'show',
    description: 'Freestyle Motocross - Sauts & figures',
    details: ['Shows a 11h45, 13h00, 15h00 & 17h00', 'Riders pros internationaux', 'Zone spectacle'],
    color: COLORS.zoneBapteme,
    mapPosition: { x: 55, y: 10 },
    coordinates: { latitude: 50.445115, longitude: 5.963667 },
  },
  // === PADDOCKS ===
  {
    id: 'paddock-f1',
    name: 'Paddock / Box F1',
    type: 'paddock',
    description: 'Paddock principal & boxes F1',
    details: [
      '#42 BDG',
      '#41 Shop BDG + Inscriptions TrackDay',
      '#40 McLaren Twins',
      '#39 Cobyx',
      '#38 RWB - Rauh-Welt Begriff',
      '#37 RWB - Rauh-Welt Begriff',
      '#36 Car Collection Sales & Gocar',
      '#35 Soul',
      '#34 Lease Club',
      '#33 GT Brothers',
      '#32 Auto Lux Concept',
      '#31 Deman Brussels',
      '#30 Motortech',
      '#29 Bavarian',
      '#28 Bavarian',
      '#27 PIT BRO',
      '#26 BCS Franzese',
      '#25 BCS Franzese & Skin',
      '#24 Loco Detailing',
      '#23 La Queen',
      '#22 Evolve Performance',
      '#21 Milwaukee',
      '#20 Milwaukee',
      '#19 Shiftech',
      '#18 Shiftech',
      '#17 Boiserie',
      '#16 Boiserie',
      '#15 La Choucoulaterie',
      '#14 Le Manoir Ink',
      '#13 LTZ Performance',
      '#12 BR Performance',
      '#11 S.T. Prototype',
      '#10 Apex Motorsport',
      '#9 Luxury Cars Center',
      '#8 GS Developpement',
      '#7 Seb Lajoux Racing',
      '#6 TrackDay Prives',
      '#5 TrackDay Prives',
      '#4 TrackDay Prives',
    ],
    color: COLORS.zonePaddock,
    mapPosition: { x: 50, y: 25 },
    coordinates: { latitude: 50.444435, longitude: 5.965445 },
    stands: [
      'F1 Red-Bull', 'RaceX & Taaqz', 'RS Tronic', 'Covering Brothers France',
      'GKR Auto Pièces', 'Xless Festival', 'Pneus d\'Or', 'Ultra Performance', 'A.F. Motorsport',
    ],
  },
  {
    id: 'paddock-violet',
    name: 'Paddock Violet',
    type: 'paddock',
    description: 'Zone stands pros & exposition',
    details: [
      'Milwaukee & Shiftech & Starfobar', 'Shine & Workshop Products and Services',
      'Born 2 Sell & Mr Ninoof', 'The Crazy Racers & 2L2D', 'Paris Interceptor',
      'Palm Adyx', 'Ceika', 'Mister Dalle', 'Route 666', 'SSC Performance',
      'Car Care Luxembourg', 'Chatreix', 'KW Suspensions', 'BR Performance',
      'RPA Toulouse', 'Vinny Art Works', 'X-1R France', 'Imagin 3D',
      'Joue Club', 'Plakperso', 'Greeen Z', 'Kennol & La Boite A Lambert',
    ],
    color: COLORS.zoneStands,
    mapPosition: { x: 60, y: 60 },
    coordinates: { latitude: 50.441353, longitude: 5.968920 },
  },
  {
    id: 'paddock-drift',
    name: 'Paddock Drift',
    type: 'paddock',
    description: 'Zone drift, dragster & demos',
    details: [
      'Show Drift : 09h30-11h, 13h30-14h30, 15h-16h',
      'Show Final Raul + Soul + Drifteurs : 16h30-17h',
      'Show Dragster : 14h30 & 16h',
    ],
    color: COLORS.primary,
    mapPosition: { x: 55, y: 75 },
    coordinates: { latitude: 50.440091, longitude: 5.969598 },
  },
  // === SERVICES & STANDS ===
  {
    id: 'shop-bdg',
    name: 'Shop BDG',
    type: 'service',
    description: 'Boutique officielle Les Brûleurs de Gommes',
    details: ['Merch officiel BDG', 'T-shirts, casquettes, stickers', 'Éditions limitées 10e anniversaire'],
    color: COLORS.zoneBapteme,
    mapPosition: { x: 50, y: 8 },
    coordinates: { latitude: 50.445276, longitude: 5.964688 },
  },
  {
    id: 'stand-pro-1',
    name: 'Stand Pro',
    type: 'service',
    description: 'Stands professionnels auto',
    details: ['Pièces & accessoires', 'Préparateurs'],
    color: COLORS.zoneStands,
    mapPosition: { x: 48, y: 12 },
    coordinates: { latitude: 50.445100, longitude: 5.964870 },
  },
  {
    id: 'pit-brasserie',
    name: 'Pit Brasserie',
    type: 'service',
    description: 'Bar, restauration & simulateurs',
    details: [
      'Bières locales & snacks',
      'DN Car Protect Simulateurs',
      'Donkervoort Prototype P24 RS',
    ],
    color: COLORS.zoneFood,
    mapPosition: { x: 55, y: 35 },
    coordinates: { latitude: 50.443406, longitude: 5.966404 },
    scheduleIds: ['5'],
  },
  {
    id: 'stand-pro-preau',
    name: 'Préau',
    type: 'service',
    description: 'Stands professionnels sous préau couvert',
    details: [
      'Les Studios Massart', 'Koi Streetwear', 'Night Led',
      'Lap Time Belgium', 'No Air Communication', 'Auto Concept Custom',
      'D-Vision', 'Jo Sticker & Jimmy Supra',
    ],
    color: COLORS.zoneStands,
    mapPosition: { x: 65, y: 35 },
    coordinates: { latitude: 50.444452, longitude: 5.966914 },
  },
  {
    id: 'fan-zone',
    name: 'Fan Zone & Kids Zone',
    type: 'service',
    description: 'Espace fans, enfants & stands pros',
    details: [
      'Shelby Gentleman Car', 'Guigui Touch', 'French Wrapping & Ma French Automobile',
      'AtomicRocketCC', 'Flashcar Cosmetics', 'All C4rz', 'LMB Modelcars',
      'Enzo\'s Shiny Cars', 'Clem Tuft', 'Velom Watches', 'Au Dreys Custom',
      'Cov\'Institut', 'Cayma Shop', 'Valentin Sportive Cars', 'JapanX',
      'Kiu Concept', 'Haribo', 'Crazy Drift', 'BW Events', 'EGR Events Kids',
    ],
    color: COLORS.zoneCircuit,
    mapPosition: { x: 70, y: 50 },
    coordinates: { latitude: 50.443429, longitude: 5.970071 },
  },
  {
    id: 'stand-pro-est',
    name: 'Stand Pro Est',
    type: 'service',
    description: 'Stands professionnels',
    details: ['Accessoires auto', 'Detailing'],
    color: COLORS.zoneStands,
    mapPosition: { x: 78, y: 40 },
    coordinates: { latitude: 50.444085, longitude: 5.971138 },
  },
  {
    id: 'stand-pro-sud',
    name: 'Stand Pro',
    type: 'service',
    description: 'Stands professionnels',
    details: ['Pièces performance', 'Accessoires'],
    color: COLORS.zoneStands,
    mapPosition: { x: 65, y: 65 },
    coordinates: { latitude: 50.441511, longitude: 5.969561 },
  },
  // === ENTREES ===
  {
    id: 'entree-ster',
    name: 'Entrée Ster',
    type: 'entrance',
    description: 'Entrée principale cote Ster',
    details: ['Contrôle des billets', 'Scan QR code', 'Distribution bracelets'],
    color: COLORS.info,
    mapPosition: { x: 80, y: 42 },
    coordinates: { latitude: 50.444926, longitude: 5.970795 },
  },
  {
    id: 'entree-la-source',
    name: 'Entrée La Source',
    type: 'entrance',
    description: 'Entrée côté virage La Source',
    details: ['Contrôle des billets', 'Accès parking P1'],
    color: COLORS.info,
    mapPosition: { x: 40, y: 5 },
    coordinates: { latitude: 50.446416, longitude: 5.962275 },
  },
];

// Practical POIs (toilets, parking, first aid, etc.)
export const MAP_POIS: MapPoi[] = [
  // WC
  { id: 'wc-1', name: 'WC Paddock F1', category: 'wc', coordinates: { latitude: 50.444200, longitude: 5.965800 } },
  { id: 'wc-2', name: 'WC Fan Zone', category: 'wc', coordinates: { latitude: 50.443600, longitude: 5.970400 } },
  { id: 'wc-3', name: 'WC Paddock Violet', category: 'wc', coordinates: { latitude: 50.441500, longitude: 5.969200 } },
  { id: 'wc-4', name: 'WC Tribune Raidillon', category: 'wc', coordinates: { latitude: 50.441400, longitude: 5.972500 } },
  // Parking
  { id: 'park-1', name: 'Parking P1 La Source', category: 'parking', coordinates: { latitude: 50.446800, longitude: 5.962000 } },
  { id: 'park-2', name: 'Parking P2 Ster', category: 'parking', coordinates: { latitude: 50.445200, longitude: 5.971500 } },
  // First aid
  { id: 'aid-1', name: 'Poste Secours', category: 'firstaid', coordinates: { latitude: 50.443800, longitude: 5.966800 } },
  { id: 'aid-2', name: 'Poste Secours Circuit', category: 'firstaid', coordinates: { latitude: 50.441000, longitude: 5.970000 } },
  // Info
  { id: 'info-1', name: 'Accueil Entrée La Source', category: 'info', coordinates: { latitude: 50.446300, longitude: 5.962500 } },
  { id: 'info-2', name: 'Accueil Entrée Ster', category: 'info', coordinates: { latitude: 50.444800, longitude: 5.970500 } },
  // Entrances
  { id: 'entrance-1', name: 'Entrée La Source', category: 'entrance', coordinates: { latitude: 50.446416, longitude: 5.962275 } },
  { id: 'entrance-2', name: 'Entrée Ster', category: 'entrance', coordinates: { latitude: 50.444926, longitude: 5.970795 } },
  // Water
  { id: 'water-1', name: 'Point d\'eau', category: 'water', coordinates: { latitude: 50.444000, longitude: 5.967000 } },
  { id: 'water-2', name: 'Point d\'eau', category: 'water', coordinates: { latitude: 50.443200, longitude: 5.970300 } },
  // Photo spot
  { id: 'photo-1', name: 'Photo Spot Raidillon', category: 'photo', coordinates: { latitude: 50.441400, longitude: 5.973000 } },
  { id: 'photo-2', name: 'Photo Spot Pit Lane', category: 'photo', coordinates: { latitude: 50.443600, longitude: 5.966000 } },
];

export const BAPTEMES: Bapteme[] = [
  {
    id: 'lmp2',
    carModel: 'Prototype LMP2 Biplace',
    provider: 'AF MotorSport',
    price: 220,
    duration: '15 min',
    laps: 3,
    description: '200 CH pour moins de 600 kg. Sensations extrêmes garanties + video 360.',
    availableSlots: [],
  },
  {
    id: 'gt3cup',
    carModel: 'Porsche 991 GT3 Cup',
    provider: 'AF MotorSport',
    price: 180,
    duration: '12 min',
    laps: 3,
    description: 'La pure-sang de course Porsche sur le plus beau circuit du monde.',
    availableSlots: [],
  },
  {
    id: 'm4comp',
    carModel: 'BMW M4 Competition',
    provider: 'Motortech',
    price: 150,
    duration: '12 min',
    laps: 3,
    description: 'M4 armée pour la piste. Puissance, freinages précis, trajectoires parfaites.',
    availableSlots: [],
  },
  {
    id: 'adrenaline',
    carModel: 'Adrenaline Experience',
    provider: 'K\'Mystik',
    price: 195,
    duration: '20 min',
    laps: 4,
    description: '4 tours inoubliables + camera embarquée avec télémétrie et vue route.',
    availableSlots: [],
  },
];
